name: Master pull request

on:
  push:
      branches: [dev]
  pull_request:
      types: [ opened ]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            name: Check out code

          - name: Check if Debug flag is on
            run: grep 'isDebug = false' public/js/common.js

